version: '3.8'

services:
  access-request-service:
    build:
      context: ./access-request-service
    env_file: ./access-request-service/.env
    ports:
      - "3001:3000"
    depends_on:
      - postgres
    environment:
      - USER_MANAGEMENT_SERVICE_HOST=user-management-service
      - USER_MANAGEMENT_SERVICE_PORT=3004

  dataset-service:
    build:
      context: ./dataset-service
    env_file: ./dataset-service/.env
    ports:
      - "3002:3000"
    depends_on:
      - postgres
    environment:
      - USER_MANAGEMENT_SERVICE_HOST=user-management-service
      - USER_MANAGEMENT_SERVICE_PORT=3004
    command: >
      sh -c "npm run seed && npm run start:dev"

  notification-service:
    build:
      context: ./notification-service
    env_file: ./notification-service/.env
    ports:
      - "3003:3000"
    depends_on:
      - postgres

  user-management-service:
    build:
      context: ./user-management-service
    env_file: ./user-management-service/.env
    ports:
      - "3004:3004"
    depends_on:
      - postgres
    command: >
      sh -c "npm run seed && npm run start:dev"

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: entitlements_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
